# Change these first
owner: mrbrant89 # Your GitHub organization or username, where this repository lives
repo: mrb-monitoring # The name of this repository

sites:
  - name: Sync Social Media [syncsocialmedia.com]
    url: https://syncsocialmedia.com
  - name: La Jolla Presbyterian Church [ljpres.org]
    url: https://ljpres.org
  - name: Vitality Integrative Wellness [growwithvitality.com]
    url: https://growwithvitality.com
  - name: Hannibal Square [hannibalsquareclt.org]
    url: https://hannibalsquareclt.org
  - name: Joy Furhman & Associates [joyfuhrman.com]
    url: https://joyfuhrman.com
  - name: Frontier Financial Planning [frontierfp.biz]
    url: https://www.frontierfp.biz
  - name: Witchland [witchlandplay.com]
    url: https://witchlandplay.com
  - name: Manage My Entity [managemyentity.com]
    url: https://managemyentity.com
  - name: Prosperity Road [prosperityroad.com]
    url: https://prosperityroad.com
  - name: A Healthy Divorce [ahealthydivorce.com]
    url: https://ahealthydivorce.com
  - name: Tailored Legal [tailoredlegal.com]
    url: https://tailoredlegal.com
  - name: Ben Aguilar, Esq. [benaguilarlaw.com]
    url: https://benaguilarlaw.com
  - name: Fleming & Associates [flemingandassociatesllc.com]
    url: https://flemingandassociatesllc.com
  - name: Kick the Fear out of Your Finances [l.kickthefearoutofyourfinances.com]
    url: https://l.kickthefearoutofyourfinances.com
  - name: CVSR Trivia Night [cvsrtrivianight.org]
    url: https://cvsrtrivianight.org
  - name: Single Oak Realty [singleoakrealty.com]
    url: https://singleoakrealty.com
  - name: The GreenHouse Group [thegreenhousegroupinc.com]
    url: https://thegreenhousegroupinc.com
  - name: Robert Ferdowsmakan [torreyhillsoms.com]
    url: https://torreyhillsoms.com
  - name: Cal-State Contractors License Service [licenses4contractors.com]
    url: https://licenses4contractors.com
  - name: San Diego Whale Watch [sdwhalewatch.com]
    url: https://sdwhalewatch.com
  - name: Peterson Reporting [petersonreporting.com]
    url: https://petersonreporting.com
  - name: Rocky Coast Builders [rockycoastbuilders.com]
    url: https://rockycoastbuilders.com
  - name: Cruise San Diego [cruise-sd.com]
    url: https://cruise-sd.com
  - name: Simone & Blevins [landlordslegalcenter.com]
    url: https://landlordslegalcenter.com
  - name: Adams Avenue [adamsavenuebusiness.com]
    url: https://adamsavenuebusiness.com
  - name: Michael Brant [michaelbrant.com]
    url: https://michaelbrant.com
  - name: MRB Development [mrbdev.com]
    url: https://mrbdev.com
  - name: MRB Hosting [mrbhost.com]
    url: https://mrbhost.com
  - name: MRB Media Inc [mrbmedia.org]
    url: https://mrbmedia.org
  - name: MR Brant [mrbrant.com]
    url: https://mrbrant.com
  - name: Where The Hell Michael [wherethehellismichael.com]
    url: https://wherethehellismichael.com
  - name: WHMCS - MRB Media [secure.mrbmedia.org]
    url: https://secure.mrbmedia.org
  - name: Distinct Construction Solutions [distinctcsolutions.com]
    url: https://distinctcsolutions.com
  - name: Thrive Coaching Academy [tcafitnesscoaching.com]
    url: https://tcafitnesscoaching.com
  - name: Smarter Wellth [smarterwellth.com]
    url: https://smarterwellth.com
  - name: Hummert Financial [hummertfinancial.com]
    url: https://hummertfinancial.com
  - name: Rae of Sunshine [raeofsunshinenaturalcare.com]
    url: https://raeofsunshinenaturalcare.com
  - name: Sagebrush Saguaro [sagebrushsaguaro.com]
    url: https://sagebrushsaguaro.com
  - name: Katalyst Wellness [katalystwellness.com]
    url: https://katalystwellness.com
  - name: Well Empowered [wellempowered.com]
    url: https://wellempowered.com
  - name: Websites That Elevate [websitesthatelevate.com]
    url: https://websitesthatelevate.com
  - name: Catalina Offshore - Online Fish Market [catalinaop.com]
    url: https://catalinaop.com
  - name: Compassion Ministries [compassionmexicoministries.org]
    url: https://compassionmexicoministries.org
  - name: New Mercy Outreach [newmercyoutreach.com]
    url: https://newmercyoutreach.com
  - name: Bedrock Retirement Partners [bedrockretirementpartners.com]
    url: https://bedrockretirementpartners.com
  - name: Bay to Bay Financial [baytobayfinancial.com]
    url: https://baytobayfinancial.com
  - name: Small Church Big Table [smallchurchbigtable.com]
    url: https://smallchurchbigtable.com
  - name: Rogers Experimental House [experimentalhouse.com]
    url: https://experimentalhouse.com
  - name: PSERC - Counselors [psercounselors.com]
    url: https://psercounselors.com
  - name: PSERC Counseling [pserchelp.com]
    url: https://pserchelp.com
  - name: Val Daniyar, DMD [valdaniyar.com]
    url: https://valdaniyar.com
  - name: Under the Clouds Spa [spa.valdaniyar.com]
    url: https://spa.valdaniyar.com
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: monitoring.mrbmedia.org
  # baseUrl: /your-repo-name
  logoUrl: https://mrbmedia.org/wp-content/uploads/2020/08/Grad-Rectangle-Dark.svg
  name: MRB Monitoring
  introTitle: "**MRB Monitoring**"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: /
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

notifications:
  NOTIFICATION_SLACK: true
  NOTIFICATION_SLACK_WEBHOOK: true
  NOTIFICATION_SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK }}

  NOTIFICATION_CUSTOM_WEBHOOK: true
  NOTIFICATION_CUSTOM_WEBHOOK_URL:	${{ secrets.GOOGLE_HOOK }}

assignees:
  - nagamrb
