# Change these first
owner: mrbrant89 # Your GitHub organization or username, where this repository lives
repo: mrb-monitoring # The name of this repository

sites:
  - name: Sync Social Media [syncsocialmedia.com]
    url: https://syncsocialmedia.com
  - name: The Resale Source [theresalesource.com]
    url: https://theresalesource.com
  - name: La Jolla Presbyterian Church [ljpres.org]
    url: https://ljpres.org
  - name: Vitality Integrative Wellness [growwithvitality.com]
    url: https://growwithvitality.com
  - name: Hannibal Square [hannibalsquareclt.org]
    url: https://hannibalsquareclt.org
  - name: Vintage Camera Box [vintagecamerabox.com]
    url: https://vintagecamerabox.com
  - name: Joy Furhman & Associates [joyfuhrman.com]
    url: https://joyfuhrman.com
  - name: Speedy Rooter [speedirooter.com]
    url: https://speedirooter.com
  - name: Frontier Financial Planning [frontierfp.biz]
    url: https://www.frontierfp.biz
  - name: Kiwi Spa [kiwi-spa.com]
    url: https://kiwi-spa.com
  - name: Witchland [witchlandplay.com]
    url: https://witchlandplay.com
  - name: Manage My Entity [managemyentity.com]
    url: https://managemyentity.com
  - name: Prosperity Road [prosperityroad.com]
    url: https://prosperityroad.com
  - name: A Healthy Divorce [ahealthydivorce.com]
    url: https://ahealthydivorce.com
  - name: Bennch Transport Services [iloilocarrentals.com]
    url: https://iloilocarrentals.com
  - name: Ivan Cazarez [ivancazarez.com]
    url: https://ivancazarez.com
  - name: Same Day Restoration [samedaydamagerestoration.com]
    url: https://samedaydamagerestoration.com
  - name: Tailored Legal [tailoredlegal.com]
    url: https://tailoredlegal.com
  - name: LMHinz Marketing [lmhinzmarketing.com]
    url: https://lmhinzmarketing.com
  - name: Ben Aguilar, Esq. [benaguilarlaw.com]
    url: https://benaguilarlaw.com
  - name: Fleming & Associates [flemingandassociatesllc.com]
    url: https://flemingandassociatesllc.com
  - name: Kick the Fear out of Your Finances [l.kickthefearoutofyourfinances.com]
    url: https://l.kickthefearoutofyourfinances.com
  - name: CVSR Trivia Night [cvsrtrivianight.org]
    url: https://cvsrtrivianight.org
  - name: Windermere Homes & Estates [whesd.com]
    url: https://whesd.com
  - name: SD County Escrow [sdcountyescrow.com]
    url: https://sdcountyescrow.com
  - name: Custom Clothing Co [customclothingco.com]
    url: https://customclothingco.com
  - name: Single Oak Realty [singleoakrealty.com]
    url: https://singleoakrealty.com
  - name: Mike's Extraordinary Soap [mikessoaps.com]
    url: https://mikessoaps.com
  - name: The GreenHouse Group [thegreenhousegroupinc.com]
    url: https://thegreenhousegroupinc.com
  - name: Robert Ferdowsmakan [torreyhillsoms.com]
    url: https://torreyhillsoms.com
  - name: Cal-State Contractors License Service [licenses4contractors.com]
    url: https://licenses4contractors.com
  - name: Sandy Asch [sandyasch.com]
    url: https://sandyasch.com
  - name: San Diego Whale Watch [sdwhalewatch.com]
    url: https://sdwhalewatch.com
  - name: Peterson Reporting [petersonreporting.com]
    url: https://petersonreporting.com
  - name: Rocky Coast Builders [rockycoastbuilders.com]
    url: https://rockycoastbuilders.com
  - name: Cruise San Diego [cruise-sd.com]
    url: https://cruise-sd.com
  - name: Simone & Blevins [landlordslegalcenter.com]
    url: https://landlordslegalcenter.com
  - name: Advanced Oxygen Therapy Inc. [aotinc.net]
    url: https://aotinc.net
  - name: Pure Structures Limited [purestructures.co.uk]
    url: https://purestructures.co.uk
  - name: Hilary Hendershott [hilaryhendershott.com]
    url: https://hilaryhendershott.com
  - name: Adams Avenue [adamsavenuebusiness.com]
    url: https://adamsavenuebusiness.com
  - name: Michael Brant [michaelbrant.com]
    url: https://michaelbrant.com
  - name: MRB Development [mrbdev.com]
    url: https://mrbdev.com
  - name: MRB Hosting [mrbhost.com]
    url: https://mrbhost.com
  - name: MRB Media Inc [mrbmedia.org]
    url: https://mrbmedia.org
  - name: MR Brant [mrbrant.com]
    url: https://mrbrant.com
  - name: Where The Hell Michael [wherethehellismichael.com]
    url: https://wherethehellismichael.com
  - name: WHMCS - MRB Media [secure.mrbmedia.org]
    url: https://secure.mrbmedia.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: monitoring.mrbmedia.org
  # baseUrl: /your-repo-name
  logoUrl: https://mrbmedia.org/wp-content/uploads/2020/08/Grad-Rectangle-Dark.svg
  name: MRB Monitoring
  introTitle: "**MRB Monitoring**"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

notifications:
  NOTIFICATION_SLACK: true
  NOTIFICATION_SLACK_WEBHOOK: true
  NOTIFICATION_SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK }}

assignees:
  - mrbrant89
  - seoanimesh07
  - nagamrb